"""empty message

Revision ID: 108727581de0
Revises: 909b0a9789a5
Create Date: 2022-12-22 19:25:25.473965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108727581de0'
down_revision = '909b0a9789a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
