"""empty message

Revision ID: 1bbc60e7e018
Revises: d9ce01558adb
Create Date: 2024-06-20 13:06:34.754608

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1bbc60e7e018"
down_revision = "d9ce01558adb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blogs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_created", sa.Date(), nullable=False),
        sa.Column("date_updated", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("accent", sa.String(length=11), nullable=False),
        sa.Column("thumbnail", sa.String(length=4096), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_blogs_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blogs")
    # ### end Alembic commands ###
