"""empty message

Revision ID: 2dcc8994b329
Revises: 7551f3119114
Create Date: 2022-11-02 19:48:48.092313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2dcc8994b329'
down_revision = '7551f3119114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id', name="pk_tags_id")
    )
    op.create_table('document_tag',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name="fk_documenttag_documentid"),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name="fk_documenttag_tagid"),
    sa.PrimaryKeyConstraint('document_id', 'tag_id', name="pk_documenttag_documentid-tagid")
    )
    op.add_column('documents', sa.Column('title', sa.String(length=128), nullable=True))
    op.add_column('documents', sa.Column('thumbnail', sa.String(length=256), nullable=True))
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('documents', 'thumbnail')
    op.drop_column('documents', 'title')
    op.drop_table('document_tag')
    op.drop_table('tags')
    # ### end Alembic commands ###
