"""Change blogs to composite primary key

Revision ID: 53f06b1d7a36
Revises: 55f8899732bc
Create Date: 2026-06-20 12:10:37.016489

"""
from alembic import op
from click.core import batch
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53f06b1d7a36'
down_revision = '55f8899732bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('_depr_requeststamps', schema=None) as batch_op:
    #     batch_op.alter_column('timestamp',
    #            existing_type=mysql.DATETIME(),
    #            nullable=False,
    #            existing_server_default=sa.text('(now())'))
    #     batch_op.alter_column('ipaddress',
    #            existing_type=mysql.VARCHAR(length=15),
    #            nullable=False)
    #     batch_op.alter_column('address_lifespan',
    #            existing_type=mysql.INTEGER(),
    #            nullable=False)
    #     batch_op.alter_column('cookie_id',
    #            existing_type=mysql.VARCHAR(length=256),
    #            nullable=False)
    #     batch_op.alter_column('request',
    #            existing_type=mysql.VARCHAR(length=32),
    #            nullable=False)



    op.drop_constraint("fk_document_tag_blog_id", "document_tag_association_table", type_="foreignkey")

    op.drop_constraint("fk_blogfeedbacks_blog_id", "blogfeedbacks", type_="foreignkey")

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Integer(), nullable=False, autoincrement=False, default=0))

        batch_op.alter_column("id", autoincrement=False, existing_type=sa.Integer(), existing_nullable=False)

        batch_op.drop_constraint("pk_blogs_id", type_="primary")
        batch_op.create_primary_key("pk_blogs_id_type", ["id", "type"])

        batch_op.alter_column("id", autoincrement=True, existing_type=sa.Integer(), existing_nullable=False)

    with op.batch_alter_table('document_tag_association_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blog_type', sa.Integer()))
        batch_op.create_foreign_key("fk_document_tag_blog_id_type", "blogs", ["blog_id", "blog_type"], ["id", "type"])

    with op.batch_alter_table('blogfeedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blog_type', sa.Integer()))
        batch_op.create_foreign_key("fk_blogfeedbacks_blog_id_type", "blogs", ["blog_id", "blog_type"], ["id", "type"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_document_tag_blog_id_type", "document_tag_association_table", type_="foreignkey")

    op.drop_constraint("fk_blogfeedbacks_blog_id_type", "blogfeedbacks", type_="foreignkey")

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        # batch_op.drop_column('type')
        # batch_op.drop_constraint("pk_blogs_id_type", type_="primary")
        # batch_op.create_primary_key("pk_blogs_id", ["id"])

        batch_op.alter_column("id", autoincrement=False, existing_type=sa.Integer(), existing_nullable=False)

        batch_op.drop_constraint("pk_blogs_id_type", type_="primary")
        batch_op.create_primary_key("pk_blogs_id", ["id"])

        batch_op.alter_column("id", autoincrement=True, existing_type=sa.Integer(), existing_nullable=False)

        batch_op.drop_column('type')

    with op.batch_alter_table('document_tag_association_table', schema=None) as batch_op:
        batch_op.drop_column('blog_type')
        batch_op.create_foreign_key("fk_document_tag_blog_id", "blogs", ["blog_id"], ["id"])

    with op.batch_alter_table('blogfeedbacks', schema=None) as batch_op:
        batch_op.drop_column('blog_type')
        batch_op.create_foreign_key("fk_blogfeedbacks_blog_id", "blogs", ["blog_id"], ["id"])

    # with op.batch_alter_table('_depr_requeststamps', schema=None) as batch_op:
    #     batch_op.alter_column('request',
    #            existing_type=mysql.VARCHAR(length=32),
    #            nullable=True)
    #     batch_op.alter_column('cookie_id',
    #            existing_type=mysql.VARCHAR(length=256),
    #            nullable=True)
    #     batch_op.alter_column('address_lifespan',
    #            existing_type=mysql.INTEGER(),
    #            nullable=True)
    #     batch_op.alter_column('ipaddress',
    #            existing_type=mysql.VARCHAR(length=15),
    #            nullable=True)
    #     batch_op.alter_column('timestamp',
    #            existing_type=mysql.DATETIME(),
    #            nullable=True,
    #            existing_server_default=sa.text('(now())'))

    # ### end Alembic commands ###
