"""empty message

Revision ID: 55f8899732bc
Revises: 56faeb7051f7
Create Date: 2025-07-20 22:33:41.616209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f8899732bc'
down_revision = '56faeb7051f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savedcomponentdiffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=1024), nullable=False))
        batch_op.add_column(sa.Column('is_safe', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savedcomponentdiffs', schema=None) as batch_op:
        batch_op.drop_column('is_safe')
        batch_op.drop_column('description')
        batch_op.drop_column('message')

    # ### end Alembic commands ###
