"""empty message

Revision ID: 56faeb7051f7
Revises: f958d947b171
Create Date: 2025-06-18 23:25:41.775598

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "56faeb7051f7"
down_revision = "f958d947b171"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "_depr_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=True),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("thumbnail", sa.String(length=256), nullable=True),
        sa.Column("content", sa.UnicodeText(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_deprdocuments_id"),
    )
    op.create_table(
        "_depr_newsletteremails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_deprnewsletteremails_id"),
    )
    op.create_table(
        "_depr_requeststamps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("ipaddress", sa.String(length=15), nullable=True),
        sa.Column("address_pool", sa.String(length=33), nullable=True),
        sa.Column("address_lifespan", sa.Integer(), nullable=True),
        sa.Column("cookie_id", sa.String(length=256), nullable=True),
        sa.Column("request", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_deprrequeststamtps_id"),
    )
    op.create_table(
        "_depr_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=True),
        sa.Column("color", sa.String(length=16), nullable=True),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_deprtags_id"),
    )
    op.create_table(
        "_depr_usersecrets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("secret", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_deprusersecrets_id"),
    )
    op.create_table(
        "_depr_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("secret_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("avatar_image", sa.String(length=256), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("phone_number", sa.String(length=64), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("password_hash", sa.String(length=256), nullable=True),
        sa.Column("is_2fa", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["secret_id"], ["_depr_usersecrets.id"], name="fk_deprusers_secret_id"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_deprusers_id"),
        sa.UniqueConstraint("email", name="uq_deprusers_email"),
        sa.UniqueConstraint("secret_id", name="uq_deprusers_secret_id"),
        sa.UniqueConstraint("username", name="uq_deprusers_username"),
    )
    op.create_table(
        "document_tag",
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"], ["_depr_documents.id"], name="fk_document_tag_document_id"
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["_depr_tags.id"], name="fk_document_tag_tag_id"
        ),
        sa.PrimaryKeyConstraint(
            "document_id", "tag_id", name="pk_document_tag_document_id_tag_id"
        ),
    )
    op.create_table(
        "_depr_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=True),
        sa.Column("is_edited", sa.Boolean(), nullable=True),
        sa.Column("content", sa.UnicodeText(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("parent_comment_id", sa.Integer(), nullable=True),
        sa.Column("parent_document_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_comment_id"],
            ["_depr_comments.id"],
            name="fk_deprcomments_parent_comment_id",
        ),
        sa.ForeignKeyConstraint(
            ["parent_document_id"],
            ["_depr_documents.id"],
            name="fk_deprcomments_parent_document_id",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["_depr_users.id"], name="fk_deprcomments_user_id"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_deprcomments_id"),
    )
    op.create_table(
        "_depr_userrecoveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("method", sa.String(length=16), nullable=True),
        sa.Column("data", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["_depr_users.id"], name="fk_depruserrecoveries_user_id"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_depruserrecoveries_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("_depr_userrecoveries")
    op.drop_table("_depr_comments")
    op.drop_table("document_tag")
    op.drop_table("_depr_users")
    op.drop_table("_depr_usersecrets")
    op.drop_table("_depr_tags")
    op.drop_table("_depr_requeststamps")
    op.drop_table("_depr_newsletteremails")
    op.drop_table("_depr_documents")
    # ### end Alembic commands ###
