"""empty message

Revision ID: 574a43d34870
Revises: f5f550cba64d
Create Date: 2022-07-10 16:52:44.354514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '574a43d34870'
down_revision = 'f5f550cba64d'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersecrets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('secret', sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.rename_table('user', 'users')

    op.add_column('users', sa.Column('secret_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'usersecrets', ['secret_id'], ['id'])
    op.create_unique_constraint("uq_users_secret_id", 'users', ['secret_id'])

    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=True))

    op.alter_column('users', 'name', nullable=False, existing_server_default="", existing_type=sa.String(length=50))
    op.create_unique_constraint("uq_users_name", 'users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('users')
    op.drop_table('usersecrets')
    # ### end Alembic commands ###
