"""Add stylesheet field to blogs

Revision ID: 61c89106c755
Revises: f56a391dc407
Create Date: 2026-08-08 01:00:06.617389

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "61c89106c755"
down_revision = "f56a391dc407"
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("blogs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("stylesheet", sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blogs", schema=None) as batch_op:
        batch_op.drop_column("stylesheet")

    # ### end Alembic commands ###
