"""empty message

Revision ID: 6c4bb9238df1
Revises: 1169638af5e8
Create Date: 2024-09-08 19:27:31.829837

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "6c4bb9238df1"
down_revision = "1169638af5e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blogs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.String(length=16), nullable=False))
        batch_op.add_column(
            sa.Column("component_lib_version", sa.Text(), nullable=False)
        )

    with op.batch_alter_table("savedcomponentdiffs", schema=None) as batch_op:
        batch_op.alter_column(
            "version",
            existing_type=mysql.VARCHAR(length=256),
            type_=sa.Text(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "next_version",
            existing_type=mysql.VARCHAR(length=256),
            type_=sa.Text(),
            existing_nullable=True,
        )

    with op.batch_alter_table("savedcomponentlibraries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("latest_version", sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("savedcomponentlibraries", schema=None) as batch_op:
        batch_op.drop_column("latest_version")

    with op.batch_alter_table("savedcomponentdiffs", schema=None) as batch_op:
        batch_op.alter_column(
            "next_version",
            existing_type=sa.Text(),
            type_=mysql.VARCHAR(length=256),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "version",
            existing_type=sa.Text(),
            type_=mysql.VARCHAR(length=256),
            existing_nullable=False,
        )

    with op.batch_alter_table("blogs", schema=None) as batch_op:
        batch_op.drop_column("component_lib_version")
        batch_op.drop_column("status")

    # ### end Alembic commands ###
