"""empty message

Revision ID: 754d7f69f4aa
Revises: 18bbd5f7d890
Create Date: 2022-07-19 12:45:55.691491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '754d7f69f4aa'
down_revision = '18bbd5f7d890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userrecoveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('data', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], 'fk_userrecoveries_users_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'recover_method')
    op.drop_column('users', 'recover_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recover_data', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('recover_method', mysql.VARCHAR(length=32), nullable=True))
    op.drop_table('userrecoveries')
    # ### end Alembic commands ###
