"""empty message

Revision ID: 7551f3119114
Revises: a79ba9acfb25
Create Date: 2022-11-02 18:21:29.613226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7551f3119114'
down_revision = 'a79ba9acfb25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name="pk_documents_id")
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('parent_document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['parent_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', name="pk_comments_id")
    )
    op.alter_column('users', 'name', new_column_name="username", existing_type=sa.String(50))
    op.add_column('users', sa.Column('avatar_image', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('is_2fa', sa.Boolean(), nullable=True))
    op.drop_column('users', 'twofa_method')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twofa_method', mysql.VARCHAR(length=32), nullable=True))
    op.alter_column('users', 'username', new_column_name="name", existing_type=sa.String(50))
    op.drop_column('users', 'is_2fa')
    op.drop_column('users', 'avatar_image')
    op.drop_table('comments')
    op.drop_table('documents')
    # ### end Alembic commands ###
