"""empty message

Revision ID: 81f8741d9424
Revises: 1bbc60e7e018
Create Date: 2024-06-21 12:36:20.381721

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "81f8741d9424"
down_revision = "1bbc60e7e018"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blogtags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=False),
        sa.Column("accent", sa.String(length=11), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_blogtags_id"),
        sa.UniqueConstraint("name", name="uq_blogtags_name"),
    )
    op.create_table(
        "document_tag_association_table",
        sa.Column("blog_id", sa.Integer(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["blog_id"], ["blogs.id"], "fk_document_tag_blog_id"),
        sa.ForeignKeyConstraint(["tag_id"], ["blogtags.id"], "fk_document_tag_tag_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_tag_association_table")
    op.drop_table("blogtags")
    # ### end Alembic commands ###
