"""empty message

Revision ID: 8584710c7a7c
Revises: 2de73f21041e
Create Date: 2024-07-06 20:57:25.734454

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8584710c7a7c"
down_revision = "2de73f21041e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blogs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("hearts", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blogs", schema=None) as batch_op:
        batch_op.drop_column("hearts")

    # ### end Alembic commands ###
