"""empty message

Revision ID: 909b0a9789a5
Revises: 2dcc8994b329
Create Date: 2022-12-19 20:43:22.145368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909b0a9789a5'
down_revision = '2dcc8994b329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requeststamps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ipaddress', sa.String(length=15), nullable=True),
    sa.Column('address_pool', sa.String(length=33), nullable=True),
    sa.Column('address_lifespan', sa.Integer(), nullable=True),
    sa.Column('cookie_id', sa.String(length=256), nullable=True),
    sa.Column('request', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requeststamps')
    # ### end Alembic commands ###
