"""empty message

Revision ID: 9e0d2f363a9c
Revises: 6c4bb9238df1
Create Date: 2024-09-27 13:55:05.064445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0d2f363a9c'
down_revision = '6c4bb9238df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savedcomponents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags_str', sa.String(length=1024), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savedcomponents', schema=None) as batch_op:
        batch_op.drop_column('tags_str')

    # ### end Alembic commands ###
