"""empty message

Revision ID: b54a8003bcd4
Revises: 574a43d34870
Create Date: 2022-07-13 12:47:23.608136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54a8003bcd4'
down_revision = '574a43d34870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('twofa_method', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('recover_data', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('recover_method', sa.String(length=32), nullable=True))
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_column('users', 'recover_method')
    op.drop_column('users', 'recover_data')
    op.drop_column('users', 'twofa_method')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
