"""Update params schema

Revision ID: f56a391dc407
Revises: 6a1c39a23a12
Create Date: 2026-07-06 12:41:47.289446

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "f56a391dc407"
down_revision = "6a1c39a23a12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("params", schema=None) as batch_op:
        batch_op.alter_column(
            "key",
            existing_type=mysql.VARCHAR(length=128),
            type_=sa.String(length=32),
            existing_nullable=False,
        )

        # batch_op.alter_column(
        #     "id",
        #     existing_type=mysql.INTEGER(),
        #     existing_nullable=False,
        #     autoincrement=False,
        # )
        batch_op.drop_column("id")
        # batch_op.drop_constraint("pk_params_id", type_="primary")

        batch_op.create_primary_key("pk_params_key", ["key"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("params", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False)
        )

        batch_op.drop_constraint("pk_params_key", type_="primary")
        batch_op.create_primary_key("pk_params_id", ["id"])

        batch_op.alter_column(
            "key",
            existing_type=sa.String(length=32),
            type_=mysql.VARCHAR(length=128),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
