"""empty message

Revision ID: f958d947b171
Revises: 9e0d2f363a9c
Create Date: 2025-06-18 00:25:26.631409

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f958d947b171"
down_revision = "9e0d2f363a9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "newsletteremails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id", name="newsletteremails_pk"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("newsletteremails")
    # ### end Alembic commands ###
