# Name of your application. Used to uniquely configure containers.
service: gabor-molnar-engineering

# Name of the container image.
image: themartinm07/gabor-molnar-engineering

# Deploy to these servers.
servers:
  web:
    - 134.199.188.153

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: false
  # Until this can be set to a proper domain name (e.g. structural-design.eu) after configuring DNS records
  #  on the domain name provider, ssl can't be enabled. That is because Let's Encrypt only works with a proper domain
  hosts:
    - structural-design.eu
    - www.structural-design.eu
    - stats.structural-design.eu
  # Proxy connects to your container on port 80 by default.
  app_port: 5000
  run:
    publish: false
    # http_port: 8080
    # https_port: 8443

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: themartinm07

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  # Pass in additional build args needed for your Dockerfile.
  # args:
  #   RUBY_VERSION: <%= ENV["RBENV_VERSION"] || ENV["rvm_ruby_string"] || "#{RUBY_ENGINE}-#{RUBY_ENGINE_VERSION}" %>

retain_containers: 1

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  clear:
    FLASK_ENV: production
    FLASK_TYPESENSE_PORT: 8108
    FLASK_TYPESENSE_HOST: gabor-molnar-engineering-typesense
    FLASK_TYPESENSE_PROTOCOL: http
    FLASK_VALIDATE_EMAIL_CHECK_DNS_SMTP: true
  secret:
    - FLASK_SECRET_KEY
    - FLASK_SQLALCHEMY_DATABASE_URI
    - FLASK_TYPESENSE_API_KEY
    - ADMIN_USERNAME
    - ADMIN_PASSWORD

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal app logs -r job" will tail logs from the first server in the job section.
#
aliases:
  vmshell: server exec --interactive "bash"
  appshell: app exec --interactive --reuse "bash"
  mysql: accessory exec db --interactive --reuse "mysql -p"
  stats: accessory exec goaccess --reuse --interactive "goaccess /var/log/nginx/access.log --log-format=COMBINED"

# Use a different ssh user than root
#
# ssh:
#   user: app

# Use a persistent storage volume.

volumes:
  - "/root/app-data:/instance"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
#
asset_path: /structdesign/static

# Configure rolling deploys by setting a wait time between batches of restarts.
#
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2

# Use accessory services (secrets come from .kamal/secrets).
#
accessories:
  db:
    image: mysql:8.0
    host: 134.199.188.153
    # The second part ":3306" is necessary to bind the container port 3306
    #  to the host machine port 3306
    port: "[::1]:3306:3306"
    env:
      clear:
        MYSQL_ROOT_HOST: "%"
      secret:
        - MYSQL_ROOT_PASSWORD
    files:
      - config/production.cnf:/etc/mysql/my.cnf
      - config/init.sql:/docker-entrypoint-initdb.d/init.sql
    directories:
      - data:/var/lib/mysql
  typesense:
    image: typesense/typesense:28.0
    host: 134.199.188.153
    # The [::1] refers to localhost (i.e. 127.0.0.1). Hence, this maps container port 8108 to port 8108 *on the localhost network* of the host machine
    #  (i.e. the VM running the docker containers). If we didn't include the "[::1]:" then this would publish the port to the outside world as well,
    #  which is not what we want
    # https://docs.docker.com/engine/network/port-publishing/#publishing-ports
    port: "[::1]:8108:8108"
    env:
      clear:
        TYPESENSE_DATA_DIR: /data
        TYPESENSE_ENABLE_CORS: "true"
      secret:
        - TYPESENSE_API_KEY:FLASK_TYPESENSE_API_KEY
    volumes:
      - ./typesense-data:/data # mount host folder for persistence

  # nginx-reverse-proxy:
  #   image: nginx:trixie-perl
  #   host: 134.199.188.153
  #   port:
  #     - "[::1]:80:80"
  #     - "[::1]:443:443"
  #   files:
  #     - config/nginx.conf:/etc/nginx/nginx.conf
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:ro
  nginx-reverse-proxy:
    # This contains a lot of very useful documentation:
    #   https://github.com/JonasAlfredsson/docker-nginx-certbot
    image: jonasal/nginx-certbot:6-alpine
    host: 134.199.188.153
    # We want these ports to be accessible to the outside world as well, hence we don't prepend "[::1]:"
    options:
      publish:
        - "80:80"
        - "443:443"
    env:
      clear:
        # "Used by Let's Encrypt to contact you in case of security issues."
        CERTBOT_EMAIL: martin.github07@gmail.com

    # directories:
    #   # Note that the :ro means "read-only"
    #   - ./config/nginx:/etc/nginx/user_conf.d:ro
    files:
      # Note that the :ro means "read-only"
      - config/nginx/structdesign.conf:/etc/nginx/user_conf.d/structdesign.conf:ro
      - .kamal/statspwd:/etc/nginx/htpasswd

    volumes:
      # - ./config/nginx:/etc/nginx/user_conf.d:ro
      - ./nginx_secrets:/etc/letsencrypt
      - /var/kamal-shared/nginx-logs:/var/log/nginx
      - /var/kamal-shared/goaccess-html:/var/www/goaccess:ro

  go-away:
    image: git.gammaspectra.live/git/go-away:0.7-alpine3.21
    host: 134.199.188.153
    port: "[::1]:8080:8080"
    env:
      clear:
        GOAWAY_BACKEND: "*=http://kamal-proxy:80"
        GOAWAY_BIND: ":8080"
        GOAWAY_CLIENT_IP_HEADER: "X-Real-IP"
        GOAWAY_METRICS_BIND: ":9090"
        GOAWAY_POLICY: "/policy.yml"
        GOAWAY_CHALLENGE_TEMPLATE: "anubis"
        GOAWAY_SLOG_LEVEL: "DEBUG"

    files:
      - ./config/go-away-policy.yml:/policy.yml:ro

  goaccess:
    image: allinurl/goaccess:latest
    host: 134.199.188.153
    volumes:
      - /var/kamal-shared/nginx-logs:/var/log/nginx:ro
      - /var/kamal-shared/goaccess-html:/var/www/goaccess
    cmd: >-
      /var/log/nginx/access.log
      -o /var/www/goaccess/index.html
      --log-format=COMBINED
      --real-time-html
      --port=7890
      --addr=0.0.0.0
      --ws-url=wss://stats.structural-design.eu:443/ws
      --geoip-database=/mmdb/dbip-asn-lite-2026-08.mmdb
      --geoip-database=/mmdb/dbip-city-lite-2026-08.mmdb

    files:
      - config/dbip/dbip-asn-lite-2026-08.mmdb:/mmdb/dbip-asn-lite-2026-08.mmdb
      - config/dbip/dbip-city-lite-2026-08.mmdb:/mmdb/dbip-city-lite-2026-08.mmdb

  # certbot:
  #   image: certbot/certbot:latest
  #   host: 134.199.188.153
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw

#   valkey:
#     image: valkey/valkey:8
#     host: 192.168.0.2
#     port: 6379
#     directories:
#       - data:/data
