import collections
import hashlib
import json
import re
import urllib.parse
import warnings
from collections.abc import Iterable
from functools import cmp_to_key
from typing import Any

from diff_match_patch import diff_match_patch
from flask import Blueprint, g, request
from sqlalchemy import select

from ..extensions import db
from ..helper import api_view
from ..models import (  # noqa: F401
    DocumentTag,
    SavedComponent,
    SavedComponentDiff,
    SavedComponentLibrary,
    SavedComponentTag,
)

bp = Blueprint("blogcreatecomponents", __name__, url_prefix="/documents")


def onfalsey(val, fallback):
    return val if val else fallback


def items_equal(a, b):
    if type(a) is not type(b):
        return False
    if type(a) is str:
        return a == b
    if isinstance(a, Iterable):
        return collections.Counter(a) == collections.Counter(b)
    return a == b


def get_component_lib():
    library = db.session.scalars(
        select(SavedComponentLibrary).filter_by(name="base")
    ).first()
    if library is None:
        raise Exception("Missing library with name 'base'")
    return library


def get_version(version: str):
    diff = db.session.scalars(
        select(SavedComponentDiff).filter_by(version=version)
    ).first()
    if diff is None:
        raise KeyError(f"Found no SavedComponentDiff for version '{version}'")
    return diff


dmp = diff_match_patch()
dmp.Patch_Margin = 1


# GENERATED BY CLAUDE
def hash(input_string, length=8):
    """
    Generate a compact, deterministic version string from input.

    Args:
        input_string (str): The string to hash
        length (int): Desired length of output (default 8)

    Returns:
        str: Compact version string using [0-9a-zA-Z]
    """
    # Base-62 characters: 0-9, a-z, A-Z
    BASE62_CHARS = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

    # Generate SHA-256 hash
    hash_bytes = hashlib.sha256(input_string.encode("utf-8")).digest()

    # Convert bytes to integer
    hash_int = int.from_bytes(hash_bytes, byteorder="big")

    # Convert to base-62
    if hash_int == 0:
        return BASE62_CHARS[0] * length

    result = ""
    while hash_int > 0 and len(result) < length:
        result = BASE62_CHARS[hash_int % 62] + result
        hash_int //= 62

    # Pad with zeros if needed
    result = result.zfill(length)

    # Truncate if longer than desired length
    return result[:length]


def create_version(comps: list[SavedComponent]):
    versions = []
    for comp in comps:
        columns = ["name", "description", "content", "parts", "tags_str"]
        comp_str = "".join([f"{key.upper()}{getattr(comp, key)}" for key in columns])
        # bytes_hash = compute_fnv128a(str.encode(comp_str))
        # versions.append(bytes_hash.hex())
        versions.append(hash(comp_str))
    return ",".join(versions)


def apply_diff(
    components: list[dict[str, Any]],
    diff: str,
) -> list[dict[str, Any]]:
    final = []

    new_name_map: dict[str, str] = {}

    new_contents_names: list[str] = g.updated_contents.copy()
    # new_removed_names: list[str] = g.removed_comps.copy()
    new_removed_names: list[str] = []

    diffs = diff.split("\\")
    # for i, diffparts in enumerate(diffs):
    i = 0
    for diffparts in diffs:

        def find_part(part: str):
            # Matches a string of non-^ (caret) characters preceded by e.g. ^NAME^
            diff_encoded = re.search(r"(?<=\^" + part.upper() + r"\^)[^^]*", diffparts)
            if not diff_encoded:
                return None
            diff_encoded = diff_encoded.group(0)
            return urllib.parse.unquote_plus(diff_encoded)

        if find_part("remove") is not None:
            # Check if this component (that will be added in a future version, hence being removed for this older version)
            #  is one that has been already removed and is in g.removed_comps (the action of an even more recent version)
            # If so, remove its name from g.removed_comps and add it to g.updated_contents because potentially the content
            #  of the component changed through this, and that would not be detected otherwise
            # -> If the content did NOT update, then that will be caught in the final checks
            # -> If a component is removed, then added, then removed again, leaving its name in g.updated_contents, then
            #     that must be handled when handling the component being removed

            if components[i]["name"] in g.removed_comps:
                # .remove() removed only first occurence of value. All elements in this list should always be unique hovever
                #  (since component names have to always be unique identifiers)
                g.removed_comps.remove(components[i]["name"])
                if components[i]["name"] not in new_contents_names:
                    new_contents_names.append(components[i]["name"])

            i += 1  # Index without appending (to `final`)
            continue

        final.append({})
        adding = find_part("add") is not None

        for part in ["name", "description", "tags", "parts", "content"]:
            if adding:
                final[-1][part] = find_part(part) or ""
                continue

            # Otherwise, what we have is a diff string

            diff_raw = find_part(part)
            # If this part (property) is not in the diff, then nothing has changed about it
            if not diff_raw:
                final[-1][part] = components[i][part] if i < len(components) else ""
                continue
            patches = dmp.patch_fromText(diff_raw)
            if i < len(components):
                new_content, _ = dmp.patch_apply(patches, components[i][part])
            else:
                new_content, _ = dmp.patch_apply(patches, "")

            final[-1][part] = new_content

            if part == "name":
                print("NAME IS BEING UPDATED")
                if latest_name := g.comp_name_map.get(components[i]["name"]):
                    new_name_map[new_content] = latest_name
                    g.comp_name_map.pop(components[i]["name"])
                else:
                    new_name_map[new_content] = components[i]["name"]
            elif part == "content":
                if components[i]["name"] not in new_contents_names:
                    new_contents_names.append(components[i]["name"])

        # When adding, append (to `final`) WITHOUT indexing
        if adding:
            new_removed_names.append(final[-1]["name"])
            if final[-1]["name"] in new_contents_names:
                new_contents_names.remove(final[-1]["name"])
        else:
            # When editing, append (to `final`) and index
            i += 1

    print("NEW_NAME_MAP:")
    print(new_name_map)
    for key, val in new_name_map.items():
        g.comp_name_map[key] = val

    inv_name_map = {v: k for k, v in g.comp_name_map.items()}
    print("INVERSE MAP:")
    print(inv_name_map)

    # Note that these diffs are going backwards in time
    g.updated_contents = [
        inv_name_map.get(last_name, last_name) for last_name in new_contents_names
    ]
    # Map previous version component names to their new names, without mapping those added in this version
    #  (as a component being added cannot have its name edited in that same version).
    g.removed_comps = [
        *[inv_name_map.get(last_name, last_name) for last_name in g.removed_comps],
        *new_removed_names,
    ]
    return final


def get_library_components(lib: SavedComponentLibrary) -> list[SavedComponent]:
    """
    Returns a reference to lib.components, after making sure the order is consistent.\n
    WHEN REFFERING TO THE COMPONENTS OF A LIBRARY. ALWAYS USE THIS FUNCTION
    """
    # It seems the order of elements in lib.components is completely consistent across
    #  all instances of the library in the application lifetime (but not across lifetimes,
    #  as the order is not saved in the database)
    # Still, it is vital that the order of components is consistent always, so that diffs
    #  always make sense and never go 'rotten'.

    # lib.components.sort(key=lambda x: x.id)
    ## Sort by ID, but don't try to sort component instances with an ID of None (which causes an error)
    ##  because they haven't been commited to the database yet.
    def compare(a, b):
        return a.id - b.id if (a.id is not None) and (b.id is not None) else 0

    key = cmp_to_key(compare)
    lib.components.sort(key=key)
    print([comp.name for comp in lib.components])

    return lib.components


@bp.route("/api/savedcomponents_currentversion")
@api_view()
def savedcomponents_currentversion():
    return get_component_lib().latest_version


@bp.route("/api/get_component_library")
@api_view()
def get_component_library():
    version = request.args.get("ver")

    lib = get_component_lib()

    if version is None:
        version = lib.latest_version

    components = [
        {
            # "id": str(comp.id),
            "name": comp.name,
            "description": comp.description,
            "tags": comp.tags_str,
            "parts": comp.parts,
            "content": comp.content,
        }
        for comp in get_library_components(lib)
    ]
    latest_components = components

    if version == lib.latest_version:
        return {
            "library": components,
            "version": lib.latest_version,
            "upgrade_to_version": lib.latest_version,
            "upgrade_name_map": {},
            "upgrade_content_list": [],
            "upgrade_remove_list": [],
            "upgrade_diff_msgs": [],
        }

    # The version (of at least one of the components) is not the latest, thus we need to take
    #  steps back in history (of diffs) until we find the requested version(s)

    current = get_version(lib.latest_version)
    current_version = current.version
    if version != "":
        # If the version IS an empty string, then this would return [''] and in the end have `final = [None]` (hence the need for special logic)
        comp_versions: list[str | None] = version.split(",")  # type: ignore
    else:
        comp_versions = []

    # Mapping from names in the requested library version (as keys) to names in the latest version (as values)
    g.comp_name_map = {comp["name"]: comp["name"] for comp in components}
    # List of names (ident names, the names as they are in the requested library version)
    g.updated_contents = []
    # List of names (same as updated_contents)
    g.removed_comps = []
    # List of object with keys "version", "message", "description"
    diff_msgs: list[dict[str, str]] = []

    # ver = current
    # while True:
    #     if not ver:
    #         break

    #     print(ver.version.split(","), " -> ", ver.next_version.split(","))
    #     print("🎈", urllib.parse.unquote_plus(ver.diff))
    #     ver = get_version(ver.next_version)
    # print("---")

    final: list[dict[str, str] | None] = [None for _ in range(len(comp_versions))]
    # print(f"{version}  Required comps num: {len(comp_versions)}\n----------")
    while True:
        current_comp_vers = current_version.split(",")
        # print(f"{current_version}  Current comps num: {len(current_comp_vers)}")
        # print(components)
        for i in range(len(comp_versions)):
            if comp_versions[i] is None:
                continue

            # print(i, len(current_comp_vers), comp_versions[i], current_comp_vers[i])
            # If we have found the match for this part of the version string
            if i < len(current_comp_vers) and comp_versions[i] == current_comp_vers[i]:
                # We cannot outright .pop() these resolved version strings, as that messes up
                #  the indices relative to current_comp_vers
                comp_versions[i] = None
                final[i] = components[i]
        # If all requested versions have been resolved, then finish
        if not any(comp_versions):
            break

        if current is None:
            return (
                f"Version history exhausted without finding the following component versions: {', '.join([ver for ver in comp_versions if ver is not None])}",
                400,
            )

        components = apply_diff(components, current.diff)
        # We want to prepend diff messages/versions, so that the order matches the
        #  chronological order of when the diffs were made.
        diff_msgs.insert(
            0,
            {
                "version": current.version,
                "message": current.message,
                "description": current.description,
            },
        )

        current_version = current.next_version
        # This will be None when at the very base of the library history, but
        #  we should still give one final check before saying the history was exhausted
        # This is why we need a separate current_version variable instead of saying
        #  current.version when defining current_comp_vers at the top of this while loop
        try:
            current = get_version(current.next_version)
        except KeyError:
            current = None

    print(final)
    print("--------")
    print(g.comp_name_map)

    ## Attempt to complete the diff message history by continuing until the diff version actually matches the requested version
    ## (instead of just when the requested version is satisfied)
    ## NOTE: This may fail (gracefully) when requesting "custom" library versions that don't match any one real version of the library

    extra_diff_msgs: list[dict[str, str]] = []
    while current_version != version:
        try:
            diff = get_version(current_version)
        except Exception:
            warnings.warn(
                "Exhausted version history trying to complete the diff messages report. Likely a custom library version was requested."
            )
            extra_diff_msgs = []
            break

        extra_diff_msgs.insert(
            0,
            {
                "version": diff.version,
                "message": diff.message,
                "description": diff.description,
            },
        )

        current_version = diff.next_version

    diff_msgs.extend(extra_diff_msgs)

    # Check for duds in the name map (where old_name == new_name)
    # for k, v in list(g.comp_name_map.items()):
    #     if k == v:
    #         g.comp_name_map.pop(k)

    # Check for duds in the content list (where old_content == new_content)
    # print(g.updated_contents)
    for old_name in g.updated_contents:
        new_name = g.comp_name_map.get(old_name, old_name)

        print(f"Old name: '{old_name}'   New name: '{new_name}'")

        old_content = next(
            comp["content"] for comp in final if comp and comp["name"] == old_name
        )
        new_content = next(
            comp["content"] for comp in latest_components if comp["name"] == new_name
        )
        if old_content == new_content:
            g.updated_contents.remove(old_name)

    return {
        "library": final,
        "version": version,
        "upgrade_to_version": lib.latest_version,
        "upgrade_name_map": g.comp_name_map,
        "upgrade_content_list": g.updated_contents,
        "upgrade_remove_list": g.removed_comps,
        "upgrade_diff_msgs": diff_msgs,
    }


"""Convert tags to list of database instances, creating tags that don't yet exist. DOESN'T COMMIT CHANGES."""


def fill_comp_tag_names(tags: list[str] | None) -> list[SavedComponentTag]:
    if not tags:
        return []

    final: list[SavedComponentTag] = []
    for tag_str in tags:
        tag = db.session.scalars(
            select(SavedComponentTag).filter_by(name=tag_str)
        ).first()
        if not tag:
            tag = SavedComponentTag(name=tag_str)
            db.session.add(tag)
        final.append(tag)
    return final


@bp.route("/api/update_components", methods=["OPTIONS", "POST"])
@api_view(methods=["OPTIONS", "POST"])
def update_components():
    """
    Handles updates, additions, and removals of components in the component library.

    This endpoint receives a JSON payload describing which components to update, add, or remove,
    verifies version consistency, applies the requested changes, generates a diff string for versioning,
    and updates the component library accordingly.

    Request (POST/OPTIONS):
        JSON body with the following keys:
            - version (str): The current version string of the component library (required for updates/removals).
            - update (dict): Mapping of component names to dictionaries of updated fields.
                Allowed fields: "name", "description", "content", "parts" (list or str), "tags" (comma-separated str).
            - add (list): List of dictionaries describing new components to add.
                Required fields: "name", "content", "parts" (list or str). Optional: "description", "tags".
            - remove (list): List of component names (str) to remove.

    Returns:
        - 200 OK with the new latest version string if changes were made.
        - 400 Bad Request with an error message if input is invalid or version mismatch occurs.
        - 200 OK with the current latest version string if no changes were made.

    Side Effects:
        - Updates the database with new, updated, or removed components.
        - Creates a new SavedComponentDiff entry for version history.
        - Updates the latest_version field of the component library.

    Example usage:
        POST /documents/update_components
        {
            "version": "abc123,def456",
            "update": {"ComponentA": {"content": "new content"}},
            "add": [{"name": "ComponentB", "content": "body", "parts": ["1"]}],
            "remove": ["ComponentC"]
        }
    """

    # RQwUepLp,7kyvhXsb,L5sIoaeY,RZKbXsiJ
    # RQwUepLp,7kyvhXsb,L5sIoaeY,RZKbXsiJ

    data: dict[str, Any] = json.loads(request.data.decode("utf-8"))
    acting_version = data.get("version", "")
    # Update: dictionary with names as keys and fields with new values. The following fields are allowed:
    #       "name": Name of the component as a string
    #       "description": Description of the component as a string
    #       "content": Content of the component as a string
    #       "parts": A list of strings of the parts of the component content (e.g. '["1", "1,1", "1,2"]')
    #       "tags": Comma-seperated list of component tag names as a string (e.g. '"tag1,tag2,tag3"')
    update: dict[str, dict[str, str | list[str]]] = data.get("update", {})
    # Add: list of dictionaries with keys like in 'update', for adding new components
    add: list[dict[str, str | list[str]]] = data.get("add", [])
    # Remove: list of strings of the names of components to remove
    remove: list[str] = data.get("remove", [])

    message: str | None = data.get("message")
    description: str | None = data.get("description")

    if (len(update) > 0 or len(remove) > 0) and acting_version is None:
        return (
            "'version' key is required when updating components (key 'update' exists) or removing components (key 'remove' exists)",
            400,
        )
    if message is None or description is None:
        return "'message' and 'description' are required", 400

    lib = get_component_lib()
    # We need the full component library, not just the ones that will be updated/removed,
    #  so that we may generate the correct diff and version string at the end
    components = get_library_components(lib)

    lib_version = lib.latest_version.split(",")
    acting_versions = acting_version.split(",")
    try:
        # If the component is one the user wants to update/remove, then we check that their version is correct
        vers_correct = [
            lib_version[i] == acting_versions[i]
            for i, comp in enumerate(components)
            if update.get(comp.name) or comp.name in remove
        ]
        if not all(vers_correct):
            errors = [
                f"'({components[i].name}' where {acting_versions[i][:8]} != {lib_version[i][:8]})"
                for i, correct in enumerate(vers_correct)
                if not correct
            ]
            return (
                f"Cannot update or remove components that aren't on their latest version. Attempted ('component' where PROVIDED_VERSION != LATEST_VERSION): {'  '.join(errors)}",
                400,
            )
    except IndexError:
        # The acting_versions may be smaller than the lib_version list
        return (
            f"Attempted to update or remove components without a provided version; provided version list (length {len(acting_versions)}) was shorter than latest version list (length {len(lib_version)})",
            400,
        )

    modified = False
    diff_parts = []

    for comp in components:
        diff_parts.append({})

        if comp.name in remove:
            # Remember, the diffs should be telling us how to get back to older versions,
            #  not how to get to this newer version
            diff_parts[-1]["ADD"] = ""
            for attr in ["name", "description", "content", "parts"]:
                diff_parts[-1][attr] = getattr(comp, attr)
            diff_parts[-1]["tags"] = comp.tags_str

            # The object will still exist in the lib.components list until committed, which
            #  luckily means no potentially weird stuff with the for loop
            db.session.delete(comp)
            modified = True
            # No need to potentially update this component when we are removing it
            continue

        comp_new_data = update.get(comp.name)
        if not comp_new_data:
            continue

        for attr in ["name", "description", "content", "parts"]:
            newval = comp_new_data.get(attr)
            if newval is not None and attr == "parts":
                newval = "|".join(newval)

            curval = getattr(comp, attr)

            if newval is not None and newval != curval:
                modified = True
                setattr(comp, attr, newval)
                diff_parts[-1][attr] = dmp.patch_toText(dmp.patch_make(newval, curval))

        # Handle "tags" separately
        newval = comp_new_data.get("tags")
        curval = comp.tags_str
        if newval is not None and newval != curval:
            modified = True
            # if type(newval) is list:
            #     newvalstr = ",".join(newval)
            newvalstr: str = ",".join(newval) if isinstance(newval, list) else newval
            # The order when we request "tags" is unreliable, thus we need to separate
            #  table column "tags_str" that gives the order. It's also useful for being
            #  the same as what's generated from the diffs
            comp.tags_str = newvalstr
            comp.tags = fill_comp_tag_names(newvalstr.split(","))
            diff_parts[-1]["tags"] = dmp.patch_toText(dmp.patch_make(newval, curval))

    for new_comp_data in add:
        if (
            new_comp_data.get("name") is None
            or new_comp_data.get("content") is None
            or new_comp_data.get("parts") is None
        ):
            return (
                f"'name', 'content' and 'parts' are required when adding new components. Attempted to add {new_comp_data}",
                400,
            )
        if isinstance(new_comp_data["parts"], list):
            new_comp_data["parts"] = "|".join(new_comp_data["parts"])

        new_comp_tags = new_comp_data.get("tags", "")
        new_comp_tagsstr = (
            ",".join(new_comp_tags)
            if isinstance(new_comp_tags, list)
            else new_comp_tags
        )

        new_comp = SavedComponent(
            name=new_comp_data.get("name"),
            description=new_comp_data.get("description", ""),
            content=new_comp_data.get("content"),
            parts=new_comp_data.get("parts"),
            tags=fill_comp_tag_names(new_comp_tagsstr.split(",")),
            tags_str=new_comp_data.get("tags", ""),
            library=lib,
        )
        # This will make the assumption that the new component will have the highest ID and so
        #  *should* appear at the end. Perhaps more shaky an assumption is that when adding
        #  multiple components at once, the given IDs by SQLAlchemy will monotonically ascend
        #  with the order in which we are appending them to lib.components
        db.session.add(new_comp)
        diff_parts.append({"REMOVE": ""})
        modified = True

    if not modified:
        return lib.latest_version

    # Create new SavedComponentDiff with
    #  version: newly created components version hash
    #  next_version: the current latest version of the library
    #  diff: patch string to get from new values to old values

    diff_str = "\\".join(
        [
            "".join(
                [
                    f"^{key.upper()}^{urllib.parse.quote_plus(val)}"
                    for key, val in dict_.items()
                ]
            )
            for dict_ in diff_parts
        ]
    )

    components_new = [
        comp for comp in get_library_components(lib) if comp not in db.session.deleted
    ]
    new_version = create_version(components_new)

    diff = SavedComponentDiff(
        version=new_version,
        next_version=lib.latest_version,
        diff=diff_str,
        message=message,
        description=description,
        is_safe=False,
    )
    db.session.add(diff)
    print("🎈 Added SavedComponentDiff with version", new_version)
    # Update latest_version of the library
    lib.latest_version = new_version

    db.session.commit()

    return lib.latest_version


@bp.route("/api/get_component_tags")
@api_view()
def get_component_tags():
    tag_names = list(db.session.scalars(select(SavedComponentTag.name)).all())
    # Dicts and lists are automatically converted to application/json mimetype responses
    return tag_names
